### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mpmdean** [mretegan/atomic-parameters#1]
Dear @mretegan 

Thanks a lot for providing this useful tool.

Despite running this previously, I now have trouble running it on my mac and i'm a little stuck. It would be really useful if you could help. This is the error I see on my mac

```
(atomic-params) markdean@10-4-31-234 atomic-parameters % python3 parameters.py --element "Fe" --configuration "1s1,3d5"

Traceback (most recent call last):
  File "/Users/markdean/Documents/programs/atomic-parameters/atomic-parameters/parameters.py", line 486, in <module>
    main()
  File "/Users/markdean/Documents/programs/atomic-parameters/atomic-parameters/parameters.py", line 477, in main
    conf.energy, conf.atomic_parameters = cowan.get_parameters()
  File "/Users/markdean/Documents/programs/atomic-parameters/atomic-parameters/parameters.py", line 440, in get_parameters
    names = self.parse_rcg_output()
  File "/Users/markdean/Documents/programs/atomic-parameters/atomic-parameters/parameters.py", line 404, in parse_rcg_output
    names = [name.format(*levels) for name in self.NAMES[key]]
KeyError: 's_with_one_particle_and_d'
```

I don't know the details of your code runs, but I get the feeling that the problem is that the underlying Fortran code might have failed? Since this problem seems to have appeared upon upgrading the OS on my mac, I was thinking that a good solution might be to write a dockerfile? 

```
FROM debian:buster as base

RUN apt-get update && apt-get install -y  python3  python3-pip python-setuptools

WORKDIR /usr/src/app

COPY * ./

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir -r requirements.txt

COPY . .
```

This seems not to work either, though. 
```
root@84959740cbe9:/usr/src/app# python3 parameters.py --element "Fe" --configuration "1s1,3d5"
CRITICAL: The command cowan/scripts/runrcn.sh did not finish successfully.
```

Presumably, I either need a different starting docker image or I am missing a dependency?

**Comment by mretegan** [comment]
@mpmdean  sorry for taking so long to get back to you.

The part of the code from this repository used to run RCN and extract the parameters for an electronic configuration is integrated now in https://github.com/mretegan/crispy. After `pip install`, you can run `python -m crispy.quanty.cowan -h` to have the same functionally.

Incidentally, I am working on this part of Crispy's code to treat cases of extracting parameters from a configuration with more than one core hole, somewhat related to the `s_with_one_particle_and_d` error you get above, but also to run RCN calculations with three subshells, for example, 1s1 3d4 4d1 (these are needed for p-d mixing).

As I will probably archive the current repository, do you need other functionally than having the parameters of an electronic configuration? RCN is enough for this, but for calculating matrix elements between configurations, I would also need to run RCN2 and RCG.

**Comment by mpmdean** [comment]
Hi @mretegan 

Thanks a lot for the note. I don't personally plan on using more than one shell, so your suggestion will work great. Thanks!
